### ISSUE TITLE
How to set the -e/--mate parameter for non-strand-specific or single-end sequencing libraries?

### ISSUE THREAD

**Issue by luckyvivi** [EMBL-Hentze-group/DEWSeq#13] opened 2024-05-21 12:28 UTC
Hi,

I have a question regarding the -e/--mate parameter for the extract command.

Sometimes sequencing library is either non-strand-specific or single-end sequencing. According to the documentation, the -e/--mate parameter is used to select the read/mate to extract the crosslink sites from paired-end sequencing, with choices 1 or 2 (1 for the first mate and 2 for the second mate).
![image](https://github.com/EMBL-Hentze-group/DEWSeq/assets/88259108/7dd11453-ec55-4b8b-a471-028a05ceed3b)
Could you please provide guidance on how to set this parameter for:

Non-strand-specific libraries
Single-end sequencing libraries

Thank you for your help!

Best regards,

**Comment by sudeepsahadevan** [comment] 2024-05-22 07:06
Closing this issue.  Duplicate of [htseq-clip issue 11](https://github.com/EMBL-Hentze-group/htseq-clip/issues/11)

**Closed as completed by sudeepsahadevan** 2024-05-22 07:06 UTC
